"""empty message

Revision ID: 8a0e112a9910
Revises: 
Create Date: 2021-10-25 04:39:23.147520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0e112a9910'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SlackTeam', sa.Column('midterm_pool_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SlackTeam', 'midterm_pool_points')
    # ### end Alembic commands ###
